export const estado = [
  ['BCN', 'MEX', 'Baja California'],
  ['BCS', 'MEX', 'Baja California Sur'],
  ['CAM', 'MEX', 'Campeche'],
  ['CHP', 'MEX', 'Chiapas'],
  ['CHH', 'MEX', 'Chihuahua'],
  ['COA', 'MEX', 'Coahuila'],
  ['COL', 'MEX', 'Colima'],
  ['DUR', 'MEX', 'Durango'],
  ['GUA', 'MEX', 'Guanajuato'],
  ['GRO', 'MEX', 'Guerrero'],
  ['HID', 'MEX', 'Hidalgo'],
  ['JAL', 'MEX', 'Jalisco'],
  ['MIC', 'MEX', 'Michoacán'],
  ['MOR', 'MEX', 'Morelos'],
  ['NAY', 'MEX', 'Nayarit'],
  ['NLE', 'MEX', 'Nuevo León'],
  ['OAX', 'MEX', 'Oaxaca'],
  ['PUE', 'MEX', 'Puebla'],
  ['ROO', 'MEX', 'Quintana Roo'],
  ['SLP', 'MEX', 'San Luis Potosí'],
  ['SIN', 'MEX', 'Sinaloa'],
  ['SON', 'MEX', 'Sonora'],
  ['TAB', 'MEX', 'Tabasco'],
  ['TAM', 'MEX', 'Tamaulipas'],
  ['TLA', 'MEX', 'Tlaxcala'],
  ['VER', 'MEX', 'Veracruz'],
  ['ZAC', 'MEX', 'Zacatecas'],
  ['CMX', 'MEX', 'Ciudad de México'],
  ['YUC', 'MEX', 'Yucatán'],
  ['QUE', 'MEX', 'Querétaro'],
  ['MEX', 'MEX', 'México'],
  ['AGU', 'MEX', 'Aguascalientes'],
]
